Updated the Helm Chart with New Image Tag Line

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,11 +35,11 @@ jobs:
     - name: Configure Git Author
       run: |
         git config --global user.name "Julius36"
-        git config --global user.email "onifadejulius36@gmail.com"
+        git config --global user.email "onifadejulius36@gmail.comgit add"
 
     - name: Update Helm CHart with New Image Tag
       run: |
-        sed -i 's/tag: .*/tag: '${{ env.SHORT_SHA }}'/g' villaja-project/values.yaml
-        git add ./villaja-project/values.yaml`
-        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
-        git push origin main
+        sed -i "s/tag: .*/tag: ${{ env.SHORT_SHA }}/g" villaja-project/values.yaml
+        git add ./villaja-project/values.yaml
+        git commit -m "Update image tag to ${{ env.SHORT_SHA }}" || echo "No changes to commit"
+        git push origin main || echo "Push failed (check permissions)"
